-- ============================================================
-- DocUNI v3.0 - Script de inicialización de datos
-- ============================================================
-- En esta versión, los datos se generan ejecutando el proceso batch
-- (crawler.py → dataIngestion.py) contra la API de Google Drive.
--
-- Este archivo se mantiene como punto de extensión para cargas
-- de datos iniciales o migraciones futuras.
-- ============================================================
